CREATE TABLE IF NOT eXISTS hardware (
id INTEGER PRIMARY KEY,
name TEXT NOT NULL,
price REAL NOT NULL
);

CREATE TABLE IF NOT eXISTS software (
id INTEGER PRIMARY KEY,
name TEXT NOT NULL,
price REAL NOT NULL
);
